### ISSUE TITLE
EPyMARL_RESCO erros

### ISSUE THREAD

**Issue by mostafanorouzi** [Pi-Star-Lab/RESCO#15]
when i run ippo, maa2c, ia2c algs, occur this error :

```
--config=ippo --env-config=gymma with env_args.time_limit=1 env_args.key=resco_benchmark:cologne8-ippo-v1
```
```
Traceback (most recent call last):
  File "/home/mostafa/pyenv/epymarl_resco/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/mostafa/pyenv/epymarl_resco/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/mostafa/pyenv/epymarl_resco/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/mostafa/pyenv/epymarl_resco/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/home/mostafa/epymarl_resco/src/main.py", line 36, in my_main
    run(_run, config, _log)
  File "/home/mostafa/epymarl_resco/src/run.py", line 55, in run
    run_sequential(args=args, logger=logger)
  File "/home/mostafa/epymarl_resco/src/run.py", line 185, in run_sequential
    episode_batch = runner.run(test_mode=False)
  File "/home/mostafa/epymarl_resco/src/runners/nstep_runner.py", line 61, in run
    self.batch.update(pre_transition_data, ts=self.t)
  File "/home/mostafa/epymarl_resco/src/components/episode_buffer.py", line 105, in update
    target[k][_slices] = v.view_as(target[k][_slices])
RuntimeError: shape '[1, 0, 240]' is invalid for input of size 240
```

**Comment by jault** [comment]
Change env_args.time_limit=1 to env_args.time_limit=10 to match the 'n' parameter set in epmarl/src/config/ippo.yaml. This information should have and will be included in the readme. Thanks for bringing it up!
